paths:
   inputdir: /lfs/f2/t2o/ptmp/emc/stmp/emc.lam/rrfs/v0.6.9/2023100207/anal_conv_dbz_gsi_spinup
   inputdir1: /lfs/f2/t2o/ptmp/emc/stmp/emc.lam/rrfs/v0.6.9/2023100207/anal_conv_dbz_gsi_spinup/background
   outputdir: ./
cyctime: 2023092418
filename: fv3_phyvars
filename1: phy_data.nc
out_nc_file: hgt
VARTYPE: ref_f3d
nmember: 36
