paths:
   inputdir: /lfs/h2/emc/ptmp/emc.lam/rrfs/v0.7.2/nwges/2022072016/fcst_fv3lam_spinup/INPUT
   outputdir: ./
cyctime: 2023112206
restartfile: phy_data.nc
gridfile: /lfs/h2/emc/lam/noscrub/emc.lam/Shun.Liu/test/rrfs_debug_tool_fix/fv3_grid_spec
filename2: fv3_tracer
out_nc_file: hgt
VARTYPE: ref_f3d
nmember: 36
