paths:
   inputdir: /lfs/h2/emc/ptmp/emc.lam/Shun.Liu
   outputdir: ./
cyctime: 2023112206
restartfile: 20231122.080000.sfc_data.nc
gridfile: /lfs/h2/emc/lam/noscrub/emc.lam/Shun.Liu/test/rrfs_debug_tool_fix/fv3_grid_spec
filename2: fv3_tracer
out_nc_file: hgt
VARTYPE: t
nmember: 36
