paths:
   inputdir: /lfs/f2/t2o/ptmp/emc/stmp/emc.lam/rrfs/v0.6.9/2023093019/anal_conv_dbz_gsi_spinup
   outputdir: ./
cyctime: 2023092418
restartfile: fv3_phyvars
gridfile: ./fv3_grid_spec
filename2: fv3_tracer
out_nc_file: hgt
VARTYPE: t
nmember: 36
