paths:
   inputdir: /lfs/h2/emc/lam/noscrub/emc.lam/Shun.Liu/test/conus
   outputdir: ./
cyctime: 2023063023
filename: phyf000.nc
out_nc_file: hgt
VARTYPE: ssmis_f17
nmember: 36
rrfsobs:
   inputdir: /lfs/h2/emc/lam/noscrub/emc.lam/Shun.Liu/test/conus/
   obs_file_name: diag_ssmis_f17_ges.2023063000.nc4
   inputna: /lfs/h2/emc/lam/noscrub/emc.lam/Shun.Liu/test/na/
   obs_file_na: diag_ssmis_f17_ges.2023070100.nc4
